

class CommonConstants:

    MULTICAST_GROUP_IP = '224.3.29.71'

    MULTICAST_PORT_VALUE = 10000

    SENDER_SOCKET_TIME_OUT = 0.2

    SENDER_SOCKET_BUFFER_SIZE = 16

    RECEIVER_SOCKET_BUFFER_SIZE = 1024

    MAXIMUM_CACHE_ELEMENT_CAPACITY = 20

    CACHE_EXPIRY_IN_SECONDS = 20

    TIME_TO_LIVE_FOR_MESSAGE = 10

    SERVER_ONE_PORT = 5253

    SERVER_TWO_PORT = 5454

